# Configuração dos Serviços do Nexus IA V1
# Este arquivo mantém o estado dos serviços necessários para cada versão

version: '1.0'

services:
  api:
    name: nexus-ia-api
    type: fastapi
    command: "uvicorn main:app --reload"
    dependencies:
      - fastapi
      - uvicorn
    env_files:
      - .env
    health_check:
      endpoint: "/health"
      interval: 30s
      
  background_tasks:
    name: nexus-ia-tasks
    type: celery
    command: "celery -A tasks worker --loglevel=info"
    dependencies:
      - celery
      - redis
    env_files:
      - .env
      
# Adicione mais serviços conforme necessário
